In [1]:
cd /private/home/ccaucheteux/hasson-syntaxe-vs-semantics

/private/home/ccaucheteux/hasson-syntaxe-vs-semantics


In [42]:
from pathlib import Path
import numpy as np

ps = list(Path("data/embeddings/0321_hugg_models/slumlordreach/").glob("*"))
ps = [p.name.split(".pth")[0] for p in ps]
#ps = ["-".join(p.split(".")[0].split("-")[:-1]) for p in ps]
np.unique(ps)

array(['3_phone_features', '3_phone_features.idx', 'n_phones', 'n_words',
       'phone_sum-bert-base-uncased-9',
       'phone_sum-bert-base-uncased-9.idx', 'phones',
       'sum-albert-base-v1-0', 'sum-albert-base-v1-1',
       'sum-albert-base-v1-10', 'sum-albert-base-v1-11',
       'sum-albert-base-v1-12', 'sum-albert-base-v1-2',
       'sum-albert-base-v1-3', 'sum-albert-base-v1-4',
       'sum-albert-base-v1-5', 'sum-albert-base-v1-6',
       'sum-albert-base-v1-7', 'sum-albert-base-v1-8',
       'sum-albert-base-v1-9', 'sum-bert-base-uncased-0',
       'sum-bert-base-uncased-1', 'sum-bert-base-uncased-10',
       'sum-bert-base-uncased-11', 'sum-bert-base-uncased-12',
       'sum-bert-base-uncased-2', 'sum-bert-base-uncased-3',
       'sum-bert-base-uncased-4', 'sum-bert-base-uncased-5',
       'sum-bert-base-uncased-6', 'sum-bert-base-uncased-7',
       'sum-bert-base-uncased-8', 'sum-bert-base-uncased-9',
       'sum-roberta-base-0', 'sum-roberta-base-1', 'sum-roberta-base-10'

In [18]:
import torch
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8]).view(4, 2)
print(x)
torch.roll(x, 2, dims=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


tensor([[5, 6],
        [7, 8],
        [1, 2],
        [3, 4]])

In [3]:
from sklearn.metrics import pairwise_distances
from sklearn.metrics.pairwise import cosine_similarity


import numpy as np
X = np.random.rand(1000, 100)
Y = X**2
zero = np.random.rand(1000, 100)
test = 1 - pairwise_distances(X, Y, "correlation")
#test = cosine_similarity(X, zero, dense_output=True)
#test.shape

In [6]:
from src.task_dataset import get_task_df
get_task_df().audio_task.unique()

array(['pieman', 'tunnel', 'slumlordreach', 'notthefallintact', 'lucy',
       'prettymouth', 'milkywayvodka', 'milkywayoriginal', 'shapessocial',
       'shapesphysical', 'merlin', 'sherlock', '21styear',
       'milkywaysynonyms', 'piemanpni', 'bronx', 'forgot', 'black'],
      dtype=object)

In [64]:
import pandas as pd
from src import paths
task_exclude = []
df = pd.read_csv(paths.base_dir / "participants.tsv", sep="\t")
df = df.astype("str")
dataset = []
for i, row in df.iterrows():
    for task, condition, comprehension in zip(
        row.task.split(","), row.condition.split(","), row.comprehension.split(",")
    ):
        if task == "milkyway":
            task = task + condition
        if task in task_exclude:
            continue
        if comprehension != "n/a":
            comprehension = float(comprehension)
            if "shapes" in task:
                comprehension /= 10
        else:
            comprehension = np.nan
        dataset.append(
            {
                "audio_task": task,
                "subject": row.participant_id,
                "comprehension": comprehension,
            }
        )
dataset = pd.DataFrame(dataset)

milkyway vodka
milkyway vodka
milkyway vodka
milkyway original
milkyway vodka
milkyway vodka
milkyway vodka
milkyway original
milkyway original
milkyway vodka
milkyway vodka
milkyway vodka
milkyway vodka
milkyway vodka
milkyway original
milkyway original
milkyway original
milkyway original
milkyway vodka
milkyway vodka
milkyway original
milkyway original
milkyway original
milkyway vodka
milkyway vodka
milkyway original
milkyway original
milkyway original
milkyway vodka
milkyway original
milkyway vodka
milkyway vodka
milkyway original
milkyway original
milkyway original
milkyway original
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms
milkyway synonyms


In [60]:
dataset.audio_task.unique()

array(['pieman', 'tunnel', 'slumlordreach', 'notthefallintact',
       'notthefallshortscram', 'lucy', 'prettymouth', 'milkyway',
       'notthefalllongscram', 'schema', 'shapessocial', 'shapesphysical',
       'merlin', 'sherlock', '21styear', 'piemanpni', 'bronx', 'forgot',
       'black'], dtype=object)

In [54]:
get_task_df().bold_task.unique()

array(['pieman', 'tunnel', 'slumlordreach', 'notthefallintact', 'lucy',
       'prettymouth', 'shapessocial', 'shapesphysical', 'merlin',
       'sherlock', '21styear', 'piemanpni', 'bronx', 'forgot', 'black'],
      dtype=object)

In [36]:
from src.encode import correlate

In [39]:
correlate(X.T, Y.T).shape

(1000,)

In [32]:
np.diag(test)

array([0.96728345, 0.96611447, 0.96864959, 0.96783504, 0.96734994,
       0.97155176, 0.96611891, 0.96811624, 0.96748595, 0.96412648,
       0.96256841, 0.96272299, 0.9671551 , 0.96966356, 0.97611183,
       0.97333199, 0.96778054, 0.9664837 , 0.96122048, 0.97539527,
       0.97410312, 0.97093278, 0.97230813, 0.96842383, 0.96387851,
       0.96501046, 0.9653913 , 0.96508706, 0.96694825, 0.96792321,
       0.96409794, 0.95942324, 0.96465529, 0.96812784, 0.96563369,
       0.96977314, 0.9705424 , 0.97327256, 0.97064912, 0.96282073,
       0.97507808, 0.96860165, 0.96265447, 0.97018494, 0.96522386,
       0.95971072, 0.96468998, 0.96944097, 0.97290156, 0.97200641,
       0.97164654, 0.97090969, 0.96607556, 0.97233416, 0.96569276,
       0.97391543, 0.9660032 , 0.97603852, 0.96388854, 0.96381068,
       0.97250516, 0.97306772, 0.97307764, 0.97114918, 0.96962233,
       0.97148362, 0.96949853, 0.96618346, 0.96707416, 0.97423067,
       0.96492407, 0.96784717, 0.97271071, 0.96587326, 0.96537

In [8]:
X.shape

(1000, 100)

In [6]:
1-pairwise_distances(X, X, "correlation").mean()

0.0010533761788330542

In [3]:
from pathlib import Path

import numpy as np
from encoding.fmri import convolve_features
from nilearn import signal
from sklearn.linear_model import RidgeCV
from sklearn.preprocessing import RobustScaler

/private/home/ccaucheteux/.conda/envs/hasson/lib/python3.8/site-packages/example_pkg_YOUR_USERNAME_HERE-0.0.1-py3.8.egg/encoding/fmri.py:11: UserWarning: 

 | Using Nistats with Nilearn versions >= 0.7.0 is redundant and potentially conflicting.
 | Nilearn versions 0.7.0 and up offer all the functionality of Nistats as well the latest features and fixes.
 | We strongly recommend uninstalling Nistats and using Nilearn's stats & reporting modules.

  from nistats.hemodynamic_models import compute_regressor


In [36]:
import time

# %load src/encode
import numpy as np
from sklearn.base import clone
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LinearRegression, RidgeCV
from sklearn.metrics import make_scorer
from sklearn.model_selection import GroupKFold, KFold
from torch_ridge import RidgeCV as TorchRidgeCV
from tqdm import tqdm

In [2]:
from src import paths
from src.encode import encode_with_folds
from src.get_bold import get_bold
from src.get_features import load_precomputed_features
from src.preprocess_stim import add_pulses_to_stim, get_stimulus
from src.task_dataset import get_task_df

In [19]:
subject = "sub-002"
audio_task = "pieman"

In [37]:
def correlate(X, Y):
    if X.ndim == 1:
        X = X[:, None]
    if Y.ndim == 1:
        Y = Y[:, None]
    X = X - X.mean(0)
    Y = Y - Y.mean(0)
    SX2 = (X ** 2).sum(0) ** 0.5
    SY2 = (Y ** 2).sum(0) ** 0.5
    SXY = (X * Y).sum(0)
    return SXY / (SX2 * SY2)

def encode(
    X,
    bold,
    estimator=RidgeCV(np.logspace(-1, 8, 20)),
    cv = KFold(5, shuffle=False),
    average_folds=True,
):
    assert use_torch == False
    model = clone(estimator)

    R = []
    for train, test in cv.split(X, groups=groups):
        print(".", end="")

        Y = bold.copy()
        model.fit(X[train], Y[train])
        X_test = X[test].copy()

        pred = model.predict(X_test)
        R.append(correlate(pred, Y[test]))

    R = np.stack(R)
    if average_folds:
        return R.mean(0)
    return R.T

In [39]:
def exp(
        subject,
        audio_task,
        space="fsaverage6",
        afni_dir=paths.afni_dir_nosmooth,
        TR=1.5,
        trim_init=2,
        scaler=RobustScaler(quantile_range=(0.1, 99.9)),
        hemi="L",  # "R"
):

    df_task = get_task_df()
    df_task = df_task.query("subject==@subject and audio_task==@audio_task")
    print(df_task)
    row = df_task.iloc[0]
    audio_onset = row.onset
    audio_task = row.audio_task
    bold_task = row.bold_task

    # Load bold responses
    gii_fname = (
        f"{subject}_task-{bold_task}_*space-{space}_hemi-{hemi}_desc-clean.func.gii"
    )
    subj_data = get_bold(gii_fname, subject, exclude=True, afni_dir=afni_dir)
    if subj_data is None:
        return

    # Trim bold w.r.t onset timing of the audio file => everything starts at 0 from now on
    subj_data = subj_data[audio_onset:, :]

    # Load stimulus
    stimuli = get_stimulus(audio_task)

    # Merge pulses and stimulus
    n_pulse = len(subj_data)
    events = add_pulses_to_stim(stimuli, n_pulse, TR=TR)

    # Cut extra pulses
    onset = np.floor(stimuli.dropna(subset=["onset"]).iloc[0].onset / TR)
    onset = int(np.max([trim_init, onset]))
    offset = np.ceil(stimuli.dropna(subset=["offset"]).iloc[-1].offset / TR)
    offset = int(offset)

    subj_data = subj_data[onset:offset]
    events = events.query("volume<@offset and volume>=@onset")
    events["volume"] -= onset
    assert len(subj_data) == len(events.query("condition=='Pulse'"))

    # Extract features
    word_events = events.query("condition == 'word'")
    word_idx = word_events.word_index.values

    feature = np.array([len(i)
                        for i in word_events.word])[:, None]  # for exemple, word len

    assert len(feature) == len(word_events)

    # Scale feature
    feature = scaler.fit_transform(feature)

    # FIR
    convolved = convolve_features(events, feat, model="fir", n_delays=4)

    # Scale FIR
    convolved = scaler.fit_transform(convolved)

    # Scale bold
    bold = subj_data.copy()
    valid = bold.std(0) > 0
    bold[:, valid] = scaler.fit_transform(bold[:, valid])

    # Encode
    r = np.zeros(bold.shape[1])
    r[valid] = encode(convolved,
                      bold[:, valid],
                      estimator=RidgeCV(np.logspace(-1, 8, 20)))

    return r

In [30]:
feature.shape

(957, 1)

In [31]:
subj_data.shape

(277, 40962)

In [8]:
    r[hemi] = {}
    for lab, feat in zip(feature_files, features):
        feat = scaler.fit_transform(feat)
        convolved = convolve_features(
            events, feat, model=convolve_model, n_delays=n_delays
        )
        convolved = scaler.fit_transform(convolved)

        # Encode
        bold = subj_data.copy()
        valid = bold.std(0) > 0
        bold[:, valid] = scaler.fit_transform(bold[:, valid])

        # CONFOUNDS
        if zero_out is not None and zero_out[lab] is not None:
            to_zero_out = list(zero_out[lab]) * n_delays
            to_zero_out = np.array(to_zero_out)
        else:
            to_zero_out = None

        if regress_out is not None and regress_out[lab] is not None:
            to_regress_out = list(regress_out[lab]) * n_delays
            to_regress_out = np.array(to_regress_out)
        else:
            to_regress_out = None

        if average_folds:
            r[hemi][lab] = np.zeros(bold.shape[1])
        else:
            r[hemi][lab] = np.zeros((bold.shape[1], n_folds))
        r[hemi][lab][valid] = encode_with_folds(
            convolved,
            bold[:, valid],
            n_folds=n_folds,
            average_folds=average_folds,
            estimator=RidgeCV(
                np.logspace(-1, 8, 10),
                fit_intercept=fit_intercept,
            ),
            to_regress_out=to_regress_out,
            to_zero_out=to_zero_out,
            groups=None,
        )

SyntaxError: invalid syntax (<ipython-input-8-056d04b3261a>, line 36)